layout_spectrum: 0.34575
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4375
  brandStrength: 0.7807018
  lightness: 0.547977
  brandColors:
    - '#A1BACC'
    - '#F1DDD6'
    - '#657886'
    - '#958A8C'
    - '#042944'
  rhythmicContrast: 0.1675608
typography_spectrum: 0.6937
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Inserat
